apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  MONGO_ROOT_USERNAME: cm9vdAo=
  MONGO_ROOT_PASSWORD: dG9pdmFiYW4K
  MONGO_USERNAME: YWRtaW4K
  MONGO_PASSWORD: dG9pdmFiYW4K
  MONGO_USERS_LIST: YWRtaW46ZGJBZG1pbixyZWFkV3JpdGU6dG9pdmFiYW4K