apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        selector: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.0.8
        env:
          - name: MONGO_INITDB_ROOT_USERNAME_FILE
            value: /etc/k8s-mongo/admin/MONGO_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD_FILE
            value: /etc/k8s-mongo/admin/MONGO_ROOT_PASSWORD
        command: ["/bin/sh"]
        args: ["-c", "mongod --bind_ip_all --dbpath=/data/db"]
        resources:
          limits:
            cpu: 1
            memory: 1500Mi
          requests:
            cpu: 1
            memory: 1000Mi
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        securityContext:
          runAsUser: 0
      tolerations:
      - key: "size"
        operator: "Equal"
        value: "large"
        effect: "NoSchedule"
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
